In [104]:
import numpy as np
import pandas as pd

In [105]:
df = pd.read_csv('ml-bugs.csv')
df

   Species  Color  Length (mm)
0    Mobug  Brown         11.6
1    Mobug   Blue         16.3
2    Lobug   Blue         15.1
3    Lobug  Green         23.7
4    Lobug   Blue         18.4
5    Lobug  Brown         17.1
6    Mobug  Brown         15.7
7    Lobug  Green         18.6
8    Lobug   Blue         22.9
9    Lobug   Blue         21.0
10   Lobug   Blue         20.5
11   Mobug  Green         21.2
12   Mobug  Brown         13.8
13   Lobug   Blue         14.5
14   Lobug  Green         24.8
15   Mobug  Brown         18.2
16   Lobug  Green         17.9
17   Lobug  Green         22.7
18   Mobug  Green         19.9
19   Mobug   Blue         14.6
20   Mobug   Blue         19.2
21   Lobug  Brown         14.1
22   Lobug  Green         18.8
23   Mobug   Blue         13.1

In [106]:
def calcEntropy(arr):
    n_total = len(arr)
    entropy = 0
    for item in set(arr):
        p_item = len(arr[arr == item]) / n_total
        entropy -= p_item*np.log2(p_item)
    return entropy

In [107]:
all = df['Species'].values
entropy = calcEntropy(all)

In [108]:
green = df[df['Color'] == 'Green'].values[:,0]
not_green = df[df['Color'] != 'Green'].values[:,0]
e_green = (calcEntropy(green) + calcEntropy(not_green)) / 2

blue = df[df['Color'] == 'Blue'].values[:,0]
not_blue = df[df['Color'] != 'Blue'].values[:,0]
e_blue = (calcEntropy(blue) + calcEntropy(not_blue)) / 2

brown = df[df['Color'] == 'Brown'].values[:,0]
not_brown = df[df['Color'] != 'Brown'].values[:,0]
e_brown = (calcEntropy(brown) + calcEntropy(not_brown)) / 2

print('Information Gain for green is {}'.format(entropy - e_green))
print('Information Gain for blue is {}'.format(entropy - e_blue))
print('Information Gain for brown is {}'.format(entropy - e_brown))

Information Gain for green is 0.07422969442158633
Information Gain for blue is 0.0017793914066928096
Information Gain for brown is 0.06157292259666325

In [109]:
for i in range(10,25):
    arr1 = df[df['Length (mm)'] < i].values[:,0]
    arr2 = df[df['Length (mm)'] >= i].values[:,0]
    e_arr = (calcEntropy(arr1) + calcEntropy(arr2)) / 2
    print('Information Gain for Length < {} is {}'.format(i, entropy - e_arr))

Information Gain for Length < 10 is 0.4899343783255764
Information Gain for Length < 11 is 0.4899343783255764
Information Gain for Length < 12 is 0.4970506899658479
Information Gain for Length < 13 is 0.4970506899658479
Information Gain for Length < 14 is 0.520720839623908
Information Gain for Length < 15 is 0.06157292259666325
Information Gain for Length < 16 is 0.054632638921391585
Information Gain for Length < 17 is 0.10240046865332442
Information Gain for Length < 18 is 0.03760783080292884
Information Gain for Length < 19 is 0.022325023633089747
Information Gain for Length < 20 is 0.18528109417543148
Information Gain for Length < 21 is 0.15485754582697575
Information Gain for Length < 22 is 0.4798687566511528
Information Gain for Length < 23 is 0.48285365091267457
Information Gain for Length < 24 is 0.4860225022032511